defaults:
  - _self_
  - datamodule: russe_dataset
  - trainer: ruroberta_trainer
  - training: ruroberta_cls_head_training
  - logging: comet_ml
  - optimizer: adamw
  - scheduler: plateau  # exponential
  - model: ruroberta
  - callbacks: ruroberta_callbacks
  - private: comet_api
#  - augmentation: basic_augs
  - loss: bce_logits
  - metric: accuracy  # metric_manager
  - inference: ruroberta_inference
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  logs_folder_name: logs
  workspace: thurs88
  project_name: sberdev-test
  device: cuda
  log_code: False
  save_pytorch_model: True
  save_best: True
  convert_to_jit: False
  checkpoint: /home/nbaranov/projects/personal/sberdev_test/outputs/2021-12-26_18-35-35/saved_models/best_epoch=10-valid_accuracy=0.8868.pth

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d_%H-%M-%S} #_${hydra.job.override_dirname}
  sweep:
    dir: ../outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
