class_name: pipeline.datasets.russe_dataset.RUSSEDataset
tokenizer: transformers.RobertaTokenizer
pretrained_tokenizer: sberbank-ai/ruRoberta-large
data_path: /home/nbaranov/projects/personal/sberdev_test/data/RUSSE/
data_module_name: pipeline.datamodules.russeperglue_datamodule.RusSuperGLUEDataModule
batch_size: 8
pin_memory: Ture
num_workers: 4
