class_name: pipeline.datasets.terra_dataset.TERRaDataset
tokenizer: transformers.RobertaTokenizer
pretrained_tokenizer: sberbank-ai/ruRoberta-large
data_path: /home/nbaranov/projects/personal/sberdev_test/data/TERRa/
data_module_name: pipeline.datamodules.russeperglue_datamodule.RusSuperGLUEDataModule
batch_size: 8
pin_memory: Ture
num_workers: 4
